#ifndef HSM_EVENT
#define HSM_EVENT

typedef enum HsmEvent{
    NO_EVENT,
    ON_DISPLAY_EVENT,
    OFF_DISPLAY_EVENT,
    UPDATE_DISPLAY_EVENT,
    DIAL_STOPPED_EVENT,
    FWD_DIAL_SLOW_EVENT,
    FWD_DIAL_FAST_EVENT,
    BWD_DIAL_SLOW_EVENT,
    BWD_DIAL_FAST_EVENT,
    MUSIC_STOP_EVENT,
    MUSIC_STOP_BEEP_EVENT,
    MUSIC_START_BEEP_EVENT,
    MUSIC_START,
} HsmEvent;

char* GET_EVENT_NAME(HsmEvent events);
#endif