#ifndef HSM_EVENT_H
#define HSM_EVENT_H

typedef enum HsmEvent{
    NO_EVENT,
    DISPLAY_ON_EVENT,
    DISPLAY_OFF_EVENT,
    DISPLAY_UPDATE_EVENT,
    DIAL_STOPPED_EVENT,
    DIAL_MOVED_FORWARD_EVENT,
    DIAL_MOVED_BACKWARD_EVENT,
    MUSIC_STOP_EVENT,
    MUSIC_STOP_BEEP_EVENT,
    MUSIC_START_BEEP_EVENT,
    MUSIC_START_FINISHED,
} HsmEvent;

char* GET_EVENT_NAME(HsmEvent events);
#endif